version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: Test-02
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Test
    ports:
      - "5433:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: Test-02
      DATABASE_USER: postgres
      DATABASE_PASSWORD: Test
      JWT_PUBLIC_KEY: 0abb78001d1c045b9993cfdbd408e5be
      JWT_PRIVATE_KEY: 8368262cbf03d587d9e8ba37e4ee77a1
      REFRESH_TOKEN_EXPIRES_IN: 3600
      ACCESS_TOKEN_EXPIRES_IN: 604800
      JWT_ALGORITHM: HS256
      TWOFACTOR_SECRET: TSRLNQJP5DE22IM6HBCC2BQB2X27W6KD
      GOOGLE_CLIENT_ID: '449721150061-eqankip4ekleq58p1qs712h8lsv0nii4.apps.googleusercontent.com'
      GOOGLE_CLIENT_SECRET: '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'
      MY_MAIL: "majdozed@gmail.com"
      MY_PASS: "nnlb qhaw xdkk okzc"
      CLOUD_NAME: "dqnwniezl"
      API_KEY: "572694926573561"
      API_SECRET: "qWWWYCvqb0ig_kTeGFk0Dr_Ar50"
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  postgres_data: