version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: ./server
    container_name: fastapi_server
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase

  client:
    build: ./client
    container_name: nextjs_client
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000

volumes:
  postgres_data: