import type { Metadata } from "next";
import { Poppins } from 'next/font/google'
import "../globals.css";
import RouteWrapper from "./components/RouteWrapper";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import Loading from "./components/Loading";
import { Suspense } from "react";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<Record<string, string | undefined>>;
}>) {
  const resolvedParams = await params;
  const locale = resolvedParams.locale;
  const messages = await getMessages({ locale });
  return (

    <html lang={locale} suppressHydrationWarning dir={locale === 'ar' ? 'rtl' : 'ltr'}>
      <body
      className={`${poppins.variable} antialiased`}
      cz-shortcut-listen="true"
      >
      {/* <PersistentLogin Children={children} /> */}

        <NextIntlClientProvider messages={messages} locale={locale}>
          <Suspense fallback={<Loading/>}>
          <RouteWrapper>
        {children} 
        </RouteWrapper>
        </Suspense>
        </NextIntlClientProvider>
            </body>
    </html>

  );
}
